require: rubocop-rspec

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 9
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/qa/linked_data_terms_controller.rb'
    - 'app/services/qa/linked_data/deep_sort_service.rb'
    - 'lib/qa/authorities/linked_data/find_term.rb'
    - 'lib/qa/authorities/linked_data/search_query.rb'
    - 'lib/qa/authorities/linked_data/config/term_config.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/qa/authorities/mesh_tools/mesh_data_parser.rb'
