inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Exclude:

Style/LineEndConcatenation:
  Exclude:

Style/PredicateName:
  Exclude:

Style/GlobalVars:
  Exclude:
    - 'spec/**/*'

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassVars:
  Exclude:

Style/SignalException:
  Enabled: false

Style/FileName:
  Exclude:

Style/VariableName:
  Exclude:
    - 'lib/share_notify/push_document.rb'

RSpec/ExampleWording:
  CustomTransform:
    be: is
    have: has
    not: does not
    NOT: does NOT
  IgnoredWords:
    - only

RSpec/ExpectActual:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/lib/tasks/mesh.rake_spec.rb'

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false
