inherit_gem:
  bixby: bixby_default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/qa/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'qa.gemspec'
    - 'spec/**/*.rb'

# By default RSpec/MessageSpies has the following:
#   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
